rsokl/MyGrad

mygrad/nnet/layers/dense.py
mygrad/nnet/layers/gru.py
tests/test_gru.py

`mygrad.nnet.layers.gru` now supports dropout on `z`, `r`, and `h`. Additionally, a major optimization is now available if back propagation through time is not truncated.
Still need to add a unit test for truncated backprop
einsum -> tensorfot for optimization

Add dropout to GRU + no-backprop-truncation optimization

---

mygrad/linalg/funcs.py
mygrad/linalg/ops.py
tests/linalg/test_einsum.py

Back-propagation via `einsum` is optimized such that any tensor that occurs
redundantly within the summation will only have its gradient computed once.
This optimization accommodates all number and combination of redundancies that can
be encountered.
E.g. back-propping through `einsum('..., ...->', x, x)` will only incur a single
computation/accumulation for `x.grad` rather than two. This permits users to
leverage the efficiency of sum-reduction, where `(x ** 2).sum()` is sub-optimal,
without being penalized during back-propagation.

Einsum opt

---

mygrad/tensor_base.py
tests/tensor_ops/test_setitem.py

(bugfix) ensure that setitem behaves appropriately when the set-variable served as multiple inputs to a function upstream in the computational graph.

(bugfix) fix edge case with setitem and topo-sort backprop

---

mygrad/tensor_base.py
mygrad/tensor_manip/array_shape/funcs.py
mygrad/tensor_manip/array_shape/ops.py

This adds the four tensor manipulation routines detailed in #90. We may want to mention somewhere the deprecated behavior of `np.expand_dims` for axis values far outside the shape:
>Note: Previous to NumPy 1.13.0, neither axis < -a.ndim - 1 nor axis > a.ndim raised errors or put the new axis where documented. Those axis values are now deprecated and will raise an AxisError in the future.
I didn't know where to mention this, so that may be worth looking at. One other small issue: since all of these functions directly wrap numpy, I copied text from the numpy documentation for some of the docstrings. Are there any plagiarism concerns with this?

Tensor manipulation routines (addresses #90)

---

setup.py
tests/linalg/test_matmul.py

The [mutually_broadcastable_shapes()](https://hypothesis.readthedocs.io/en/latest/numpy.html#hypothesis.extra.numpy.mutually_broadcastable_shapes) strategy [now accepts gufunc signatures](https://hypothesis.readthedocs.io/en/latest/changes.html#v4-44-0) to determine the shapes it generates. 
This allows us to remove all of the special cases and manually-specified shapes that we were constructing for the `mygrad.matmul` tests - the generated test cases are significantly more diverse!

Matmul test refactor

---

tests/linalg/test_multi_matmul.py
tests/wrappers/uber.py

The [mutually_broadcastable_shapes()](https://hypothesis.readthedocs.io/en/latest/numpy.html#hypothesis.extra.numpy.mutually_broadcastable_shapes) strategy [now accepts gufunc signatures](https://hypothesis.readthedocs.io/en/latest/changes.html#v4-44-0) to determine the shapes it generates. 
This eliminates the huge burden that we faced of generating custom chains of matmul-compatible shapes!

Multi matmul tests

---

docs/source/generated/mygrad.repeat.rst
docs/source/tensor_manipulation.rst
mygrad/__init__.py
mygrad/tensor_manip/tiling/funcs.py
mygrad/tensor_manip/tiling/ops.py
tests/test_tensor_manip.py

Add mygrad.repeat operation

---

tests/linalg/test_einsum.py
tests/nnet/test_gru.py

Closes #178 
Thank you @Zac-HD for catching this! I don't have a job that runs against old NumPy

fix backwards inequality for einsum-opt test

---

src/mygrad/nnet/activations/sigmoid.py
tests/nnet/activations/test_sigmoid.py

Closes #182
Also fixes this error I found:
``` python
Python 3.6.4 |Anaconda, Inc.| (default, Mar 13 2018, 01:15:57) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.7.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from mygrad.nnet import sigmoid                                                                                        
In [2]: sigmoid(0)                                                                                                             
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-543cf44917cb> in <module>
----> 1 sigmoid(0)
/opt/conda/envs/lab42/lib/python3.6/site-packages/mygrad/nnet/activations/sigmoid. …
```

Fix sigmoid, add test

---

src/mygrad/__init__.py
src/mygrad/indexing_routines/funcs.py
src/mygrad/linalg/funcs.py
src/mygrad/math/arithmetic/funcs.py
src/mygrad/math/exp_log/funcs.py
src/mygrad/math/hyperbolic_trig/funcs.py
src/mygrad/math/misc/funcs.py
src/mygrad/math/sequential/funcs.py
src/mygrad/math/trigonometric/funcs.py
src/mygrad/nnet/activations/relu.py
src/mygrad/nnet/activations/sigmoid.py
src/mygrad/nnet/activations/softmax.py
src/mygrad/nnet/layers/batchnorm.py
src/mygrad/nnet/layers/conv.py
src/mygrad/nnet/layers/gru.py
src/mygrad/nnet/layers/pooling.py
src/mygrad/nnet/losses/margin_ranking_loss.py
src/mygrad/nnet/losses/multiclass_hinge.py
src/mygrad/nnet/losses/softmax_crossentropy.py
src/mygrad/tensor_base.py
src/mygrad/tensor_manip/array_shape/funcs.py
src/mygrad/tensor_manip/array_shape/ops.py
src/mygrad/tensor_manip/tiling/funcs.py
src/mygrad/tensor_manip/transpose_like/funcs.py
tests/custom_strategies/__init__.py
tests/custom_strategies/test_strategies.py
tests/tensor_base/test_op_wrapper.py
tests/tensor_ops/test_reshape.py
tests/wrappers/uber.py

Closes #197 
- Generalizes in-place operations on `Tensor`
- Fixes inconsistent interface between `Tensor.reshape` and `numpy.reshape`
- Fixes inconsistent param name between `mygrad.reshape` and `numpy.reshape`
- Makes `.shape`  settable
- Greatly improve tests for `reshape`
- Rename confusing internal param name to be more descriptive

Settable shape

---

tests/nnet/activations/test_hard_tanh.py

`maximum` and `minimum` do not have derivatives at their clip boundaries - have test avoid these edge cases

hardnet_tanh: ensure test avoids overlapping bounds with data

---

tests/nnet/activations/test_leaky_relu.py

What's the right way to fix this? The issue is that the actual slope value is ok but the gradient being passed back through this operation is randomly in (-10, 10) which can cause an inf

Hotfix leaky relu test

---

src/mygrad/nnet/initializers/__init__.py
src/mygrad/nnet/initializers/normal.py
tests/nnet/initializers/test_normal.py

Last one :sweat_smile: 
Do we want to put `normal` and `uniform` into `tensor_creation` as well? Are we going to mirror `np.random` in the future?

Add normal initializer

---

src/mygrad/nnet/layers/gru.py
tests/nnet/layers/test_gru.py

Closes #261 
Casts all parameters to the biggest dtype for any forward- or backward-pass calls to numba, and recasts to original data types as necessary when passing back gradients. Also updates GRU tests to check for both float32 and float64s.
The tests currently only have the data `X` as float64, as I am unsure of how to draw an array in the `given` decorator that has the `dtype` argument and `width` argument of `st.floats` agree

float32 and float64 compatability in GRU

---

setup.cfg

TravisCI has old LLVM for py36: ensure llvmlite < 34.0 is run for py36

---

src/mygrad/tensor_base.py
tests/state_testing/test_state.py
tests/tensor_base/test_tensor.py
tests/tensor_ops/test_getitem.py
tests/tensor_ops/test_iter.py

Reverts #267 
There were tons of problems with setting Tensor.constant after it was already involved in a computational graph. The state-based testing found this, but needed to traverse deeper to find the problems consistently.
E.g.
```python
v1 = Tensor(0.)
v2 = +v1
v3 = Tensor(0.)
v4 = v3 - v2
v4.constant = True
v5 = v4 + v2
v5.backward()
```
would fail to clear `v2._accum_ops` during backprop. Another fail case: https://travis-ci.com/github/rsokl/MyGrad/jobs/372350422#L395
I considered only partially restricting the user's ability to set constant, but it just created too many headaches.
As an alternative, users can now use `Tensor.copy(constant)` to a similar, but sanitized, effect

remove ability to set Tensor.constant

---

.gitignore
src/mygrad/linalg/ops.py
src/mygrad/operation_base.py
src/mygrad/tensor_base.py
tests/tensor_base/test_tensor.py

Normally python would have made `Tensor` unhashable, but because this is being monkeypatched, it wasn't able to.
You would think this PR is a noop, but it'll cause a bunch of 'unhashable type: Tensor' errors
Ryan Edit:
Any class with `__eq__` defined will have that method be used to check hash-table collisions. `Tensor.__eq__` is based on its underlying numpy array, which is mutable. Also, this method returns an array, not a boolean – making it even more inappropriate. I.e. `Tensor` should have been unhashable.
`Tensor` _was_ hashable – and we relied on this hashability for doing BFS traversals of the computational graph – but this was a fluke. It was because `__eq__` and `__neq__` was getting monkeypatched after the `Tensor` definition. So basically, Python was falling back on its …

Demonstrate that python3 wants to warn you not to override __eq__ withou __hash__

---

setup.py
src/mygrad/linalg/funcs.py
src/mygrad/math/arithmetic/ops.py
src/mygrad/math/sequential/ops.py
src/mygrad/operation_base.py
src/mygrad/tensor_base.py
tests/custom_strategies/__init__.py
tests/custom_strategies/test_strategies.py
tests/linalg/test_einsum.py
tests/tensor_base/test_pow_special_cases.py
tests/tensor_base/test_shares_memory.py
tests/tensor_ops/test_getitem.py
tests/tensor_ops/test_iter.py
tests/tensor_ops/test_reshape.py
tests/wrappers/uber.py

This PR adds rudimentary functionality for tracking views of tensors. This is the beginnings of adding support for completely generic in-place updates on views of tensors.
Like `ndarray.base`, `Tensor.base` provides the ability to track views of Tensors. 
The base of a tensor that owns its memory is `None`:
```python
>>> import mygrad as mg
>>> x = mg.arange(5)
>>> x.base is None
True
```
Slicing creates a view, whose memory is shared with `x`:
```python
>>> y = x[2:]
>>> y.base is x
True
>>> y.data.base is x.data
True
```
A view of a view has the same base as its "parent"
```python
>>> z = y[:]
>>> z.base is x
True
```
The behavior of `Tensor.base` departs from that of `ndarray.base` in that
mygrad will never create an "internal" tensor to serve as a base; e.g.
```python
>>> import numpy …
```

Add Tensor.base

---

src/mygrad/__init__.py
src/mygrad/_graph_tracking.py
src/mygrad/math/sequential/ops.py
src/mygrad/nnet/activations/softmax.py
src/mygrad/nnet/losses/focal_loss.py
src/mygrad/nnet/losses/margin_ranking_loss.py
src/mygrad/nnet/losses/multiclass_hinge.py
src/mygrad/nnet/losses/softmax_crossentropy.py
src/mygrad/operation_base.py
src/mygrad/tensor_base.py
tests/__init__.py
tests/math/sequence/test_sequential_funcs.py
tests/nnet/layers/test_batchnorm.py
tests/nnet/layers/test_conv.py
tests/nnet/losses/test_focal_loss.py
tests/nnet/losses/test_softmaxcrossentropy.py
tests/state_testing/test_state.py
tests/tensor_base/test_no_null_grad_semantics.py
tests/tensor_base/test_pow_special_cases.py
tests/test_no_autodiff.py

@aslvrstn @Zac-HD if you wouldn't mind taking a look at [`src/mygrad/_graph_tracking.py`](https://github.com/rsokl/MyGrad/blob/1253c23071d966165484678a1cff29b08ae4b35e/src/mygrad/_graph_tracking.py), I'd like to get your thoughts on if this implementation for a global flag is sensible, or if there are some details/precautions that I should heed
Adds `mygrad.no_autodiff`, which is a context manager and decorator that temporarily disables all of mygrad's graph-tracking and memory-locking logic.
```python
from mygrad import no_autodiff, arange
x = arange(10.)
with no_autodiff:
y = 2 * x  # creates a constant tensor with no creator
```
```python
@no_autodiff
def forward_pass():
pass
````
You can also effectively convert mygrad functions to their numpy counterparts now:
```python
import mygrad …
```

Add no graph mode

---

src/mygrad/_utils/lock_management.py
src/mygrad/nnet/layers/batchnorm.py
src/mygrad/nnet/layers/gru.py
src/mygrad/tensor_base.py
tests/conftest.py
tests/nnet/layers/test_gru.py
tests/state_testing/test_state.py
tests/tensor_base/test_memory_locking.py
tests/tensor_ops/test_reshape.py
tests/test_duplicating_graph.py
tests/test_in_place_semantics.py
tests/test_tensor_creation.py
tests/utils/__init__.py
tests/wrappers/test_uber.py

- bugfixes 
- unlock view of locked-&-tracked array; handle multiple views waiting for same base for unlock
- don't force-lock output; was causing read-only tensors to get tracked by mem-locker
- batchnorm wasn't clearing its state properly for gamma/beta=none
- fix ref cycles in GRU
-  clean up stragglers in `_views_waiting_for_unlock` if no tracked arrays remain
Ensure tests don't leak state

More mem lock tests

---

docs/source/generated/mygrad.Tensor.base.rst
docs/source/tensor.rst
src/mygrad/nnet/initializers/glorot_normal.py
src/mygrad/nnet/initializers/normal.py
src/mygrad/nnet/initializers/uniform.py
src/mygrad/nnet/losses/negative_log_likelihood.py
src/mygrad/random/funcs.py
src/mygrad/tensor_base.py
src/mygrad/tensor_creation/funcs.py
tests/custom_strategies/__init__.py
tests/custom_strategies/test_strategies.py
tests/tensor_base/test_tensor.py

- `Tensor(..., copy=<val>)` now matches `array(..., copy=<val>)`
- Added `Tensor(..., ndmin=<val>)`, to match that of `array`
- Improves some docs

Improve parity between Tensor.__init__ and array.__init__

---

setup.cfg
tests/conftest.py
tests/tensor_base/test_memory_locking.py

Running tests under coverage mode can sometimes lead to leaky state associated with the memory guard mechanism. A fixture will raises if that happens - causing the coverage run to fail. Now that fixture will only warn and cleanup during coverage.

Fix flaky coverage

---

src/mygrad/_utils/__init__.py
src/mygrad/tensor_base.py
tests/custom_strategies/__init__.py
tests/tensor_base/test_backward.py
tests/tensor_base/test_tensor.py
tests/test_utils.py

`tensor.backward(grad)` now supports `grad`  that can be broadcast into `tensor`. The resulting `tensor.grad`  will be cast to the correction (floating) dtype.

Make tensor.backward() support broadcasting and type-casting

---

tests/tensor_base/test_operator_override.py

With numpy's fancy mechanisms for dispatching, it is important to explicitly test that the main mathematical operators dispatch appropriately

test math operators explicitly

---

src/mygrad/_tensor_core_ops/indexing.py
src/mygrad/_utils/duplicating_graph.py
src/mygrad/indexing_routines/ops.py
src/mygrad/linalg/ops.py
src/mygrad/math/arithmetic/ops.py
src/mygrad/math/exp_log/ops.py
src/mygrad/math/hyperbolic_trig/ops.py
src/mygrad/math/misc/ops.py
src/mygrad/math/sequential/funcs.py
src/mygrad/math/sequential/ops.py
src/mygrad/math/trigonometric/ops.py
src/mygrad/operation_base.py
src/mygrad/tensor_base.py
src/mygrad/tensor_manip/array_shape/ops.py
src/mygrad/tensor_manip/tiling/ops.py
src/mygrad/test_ufuncs.py
tests/test_in_place_semantics.py
tests/test_operation_base.py
tests/test_ufuncs.py

Implements an ergonomic and intuitive hierarchy of `Operation` subclasses. Among these is the `Ufunc` base class, which permits MyGrad's operations to easily match the interface of numpy's many ufuncs. 
Ultimately, this PR will will enable MyGrad to leverage [the interfaces `__array_ufunc__` and `__array_function__`](https://numpy.org/doc/stable/user/basics.dispatch.html). Additionally, it makes it much easier for MyGrad to support specifying `out`, `where`, and `dtype` on a large majority of its operations.

Operation refactoring

---

src/mygrad/_utils/__init__.py
src/mygrad/tensor_base.py
tests/tensor_base/test_no_null_grad_semantics.py
tests/test_view_semantics.py

View operations no longer clear gradients. This allows the intuitive workflow of taking a view of a tensor to glean its corresponding gradient
```python
>>> base = mg.arange(4.0)
>>> (base ** 2).backward()
>>> view = base[-2:]
>>> base.grad, view.grad
(array([0., 2., 4., 6.]), array([4., 6.]))
```
This also removes a previously-tolerated inconsistency where a nulled grad for a base tensor would not null the grad for a view.

view operations no longer null grads

---

src/mygrad/indexing_routines/funcs.py
src/mygrad/linalg/funcs.py
src/mygrad/linalg/ops.py
src/mygrad/math/misc/funcs.py
src/mygrad/math/sequential/funcs.py
src/mygrad/random/funcs.py
src/mygrad/tensor_base.py
src/mygrad/tensor_creation/funcs.py
src/mygrad/tensor_manip/array_shape/funcs.py
src/mygrad/tensor_manip/tiling/funcs.py
src/mygrad/tensor_manip/transpose_like/funcs.py
tests/linalg/test_einsum.py
tests/math/sequence/test_sequential_funcs.py
tests/math/test_misc.py
tests/tensor_ops/test_reshape.py
tests/tensor_ops/test_setitem.py
tests/test_in_place_semantics.py
tests/test_indexing_routines.py
tests/test_numpy_override.py
tests/test_tensor_manip.py
tests/ufuncs/test_fwd_prop_and_backprop.py
tests/utils/functools.py
tests/wrappers/test_uber.py

closes #220
The existing mygrad-mirrors for numpy functions now override those functions when they operate on a tensor:
```python
>>> x = mg.tensor([2., -1., 0.])
>>> numpy.einsum("i,i", x, x).backward()
>>> x.grad
array([ 4., -2.,  0.])
```

add __array_function__ implementation 

---

docs/source/generated/mygrad.concatenate.rst
docs/source/tensor_manipulation.rst
src/mygrad/__init__.py
src/mygrad/operation_base.py
src/mygrad/tensor_manip/tensor_joining/funcs.py
src/mygrad/tensor_manip/tensor_joining/ops.py
tests/test_tensor_joining.py

Co-authored-by: Petar Griggs <petargriggs@gmail.com>
```python
>>> import mygrad as mg
>>> x = mg.tensor([[2., -1., 0.]], constant=False)
>>> o = np.concatenate([x, x, x], axis=0)
>>> o
Tensor([[ 2., -1.,  0.],
[ 2., -1.,  0.],
[ 2., -1.,  0.]])
>>> o.backward()
>>> x.grad
array([[3., 3., 3.]])
```
I plan to add the other joining functions in separate PRs

Adds mygrad.concatenate

---

src/mygrad/linalg/funcs.py
src/mygrad/linalg/ops.py
src/mygrad/math/misc/funcs.py
src/mygrad/math/misc/ops.py
src/mygrad/tensor_creation/funcs.py
src/mygrad/ufuncs/_ufunc_creators.py
tests/linalg/test_norm.py
tests/ufuncs/test_fwd_prop_and_backprop.py

(I also smuggled in a fix for `mygrad.arange` that normalizes its interface with that of `numpy.arange`
Now both `mygrad.linalg.norm` and `mygrad.absolute`, by default, will return `0` wherever their derivatives would typically not defined (and would previously have returned `nan`).
Both of these functions can be passed `nan_to_num=False` to enable the previous, more-rigorous, behavior.
Before:
```python
>>> import mygrad as mg
>>> x = mg.tensor([-2.0, 0.0, 2.0])
>>> mg.absolute(x).backward()
>>> x.grad
array([-1., nan,  1.])
```
After:
```python
>>> import mygrad as mg
>>> x = mg.tensor([-2.0, 0.0, 2.0])
>>> mg.absolute(x).backward()
>>> x.grad
array([-1., 0.,  1.])
>>> mg.absolute(x, nan_to_num=False).backward()
>>> x.grad
array([-1., nan,  1.])
```

Update default behavior of derivative of linalg.norm and abs at x=0

---

src/mygrad/math/misc/funcs.py
src/mygrad/tensor_base.py
tests/math/test_misc.py

Implement clip(..., out=)

---

src/mygrad/_utils/__init__.py
src/mygrad/_utils/duplicating_graph.py
src/mygrad/math/arithmetic/ops.py
src/mygrad/nnet/initializers/__init__.py
src/mygrad/nnet/layers/gru.py
src/mygrad/operation_base.py
src/mygrad/tensor_base.py
tests/state_testing/test_simple_graph_state.py
tests/tensor_base/test_augmented_updates.py
tests/tensor_base/test_chainrule.py
tests/tensor_base/test_no_null_grad_semantics.py
tests/tensor_ops/test_setitem.py

Traversing the graph based on tensors, not operations, makes things much nicer!

Simplify back-prop scheme

---

setup.py
src/mygrad/tensor_base.py
src/mygrad/typing/_array_like.py
src/mygrad/typing/_dtype_like.py
src/mygrad/typing/_shape.py
tests/custom_strategies/__init__.py
tests/tensor_base/test_augmented_updates.py

numpy 1.25.0 causes `tests/tensor_ops/test_getitem.py::test_getitem_advindex_bool_bkwdprop` to segfault :(

fix registered hypothesis strategies and ban numpy 1.25.0
