rsokl/MyGrad

README.md, mygrad/computational_graph.py, mygrad/tensor_base.py
Adds network graphs using ~~pydot and~~ graphviz
=> Network Graphs

mygrad/nnet/activations.py, tests/nnet/test_softmax.py
remove potential for unintended side effects in `softmax.backward`; add softmaxt/logsoftmax tests for 1D case
=> refactor softmax & logsoftmax code; 

mygrad/math/arithmetic/funcs.py, mygrad/math/arithmetic/ops.py, mygrad/math/exp_log/funcs.py, mygrad/math/exp_log/ops.py, mygrad/math/trigonometric/funcs.py, mygrad/math/trigonometric/ops.py, tests/math/binary/test_binary_funcs.py, tests/math/unary/test_arithmetic.py, tests/math/unary/test_exp.py
Here are the three functions from #87.
I'm not entirely sure what I'm doing with the unit tests so they are mostly copied and pasted - nothing happened when I ran them so I assume that's a good thing.
=> add square, exp2, and arctan2

doc/source/generated/mygrad.Tensor.flatten.rst, doc/source/generated/mygrad.broadcast_to.rst, doc/source/generated/mygrad.expand_dims.rst, doc/source/generated/mygrad.ravel.rst, doc/source/tensor_manipulation.rst, mygrad/tensor_base.py, mygrad/tensor_manip/array_shape/funcs.py, mygrad/tensor_manip/array_shape/ops.py, tests/custom_strategies/__init__.py, tests/test_tensor_manip.py, tests/wrappers/uber.py
Revision of #103 
@IanCoolidge0 this was a fantastic PR. Thank you! I had to open a new PR off of your branch so that I could add doc pages and unit tests.
Regarding the concern with plagiarism, I have added a line in each docstring to explicitly note that they are adaptations of the corresponding numpy docs. I believe that this is a totally suitable way of dealing with that.
=> Flatten routines

mygrad/nnet/losses.py, tests/math/binary/test_binary_funcs.py, tests/math/unary/test_arithmetic.py, tests/math/unary/test_trigonometric.py, tests/nnet/test_batchnorm.py, tests/nnet/test_gru.py, tests/nnet/test_recurrent.py, tests/tensor_ops/test_setitem.py, tests/test_tensor_manip.py, tests/utils/test_utils.py
- fix bad deadlines
- fix bad tolerances
=> (tests) upgrade to hypothesis 4.X

mygrad/operation_base.py, tests/custom_strategies/__init__.py, tests/state_testing/test_state.py, tests/tensor_base/test_chainrule.py
fixes breaking change to backprop from 337463c; consolidates backward implementations in Op; adds regression tests; increases examples of stateful testing
And fixes breaking change to 8b53fd9
=> fixes breaking change to backprop from #337463c

docs/README.md, docs/source/intro.rst
=> Fixed some typos

mygrad/tensor_base.py, tests/state_testing/simple_graph.py
Fixes null-gradient graph traversal such that visited nodes are skipped 🎉 🙌 
We no longer have any issues with nulling through the graph of a recurrent neural network
=> Optimize null-gradients graph-traversal

mygrad/tensor_base.py
=> null_gradients(clear_graph=True) now does a single graph traversal

docs/source/math.rst, setup.py, tests/linalg/test_multi_matmul.py, tests/math/binary/test_binary_funcs.py, tests/nnet/test_conv.py, tests/tensor_ops/test_sequence_ops.py, tests/wrappers/uber.py
=> Integrate mutually-broadcastable shapes strategy into tests

setup.py, tests/linalg/test_multi_matmul.py, tests/math/sequence/test_sequential_funcs.py, tests/state_testing/test_state.py, tests/wrappers/uber.py
Hypothesis [reorganized their internals](https://hypothesis.readthedocs.io/en/latest/changes.html#v4-53-2)... but I import from their internals in my test suite. Had to update the import to fix CI.
=> Fix test suite

tests/nnet/activations/test_sigmoid.py
=> fix bounds on sigmoid test

tests/math/test_misc.py
=> require numpy 1.17 or later for mygrad.clip tests

src/mygrad/math/misc/funcs.py
See: https://github.com/numpy/numpy/pull/15579
=> fix clip docs

src/mygrad/tensor_base.py, tests/tensor_base/test_astype.py
=> adds Tensor.astype

src/mygrad/nnet/activations/softmax.py, tests/nnet/activations/test_softmax.py
Fixes #193 
will add a test for this. The softmax tests are 🤨
=> Fix softmax

src/mygrad/tensor_base.py, tests/tensor_base/test_tensor.py
Fixes https://github.com/rsokl/MyGrad/issues/210
This is technically a breaking change I think, in that theoretically someone could be depending on it. Up to you how much to worry about that.
=> Iteration over 0D tensor should raise type error

tests/wrappers/uber.py
As discussed, this PR illustrates how to fix collisions from test factories in the Hypothesis example database... without actually fixing them.  But you can take it from here and I'll review it at the end :grin:
=> Distinguish backprop tests for Hypothesis example DB

tests/nnet/activations/test_glu.py
=> fix flaky glu test

src/mygrad/nnet/initializers/__init__.py, src/mygrad/nnet/initializers/glorot_normal.py, tests/nnet/initializers/test_glorot_normal.py
`test_glorot_normal_statistics` seems a little silly. We're basically testing that `np.random.normal` works :/ anything better we can do?
=> Add glorot normal initializer

tests/wrappers/uber.py
ensure fwd-uber tests combinations of constant/non-constant input tensors
(fixes lack of coverage in #244)
=> Test constant combinations

src/mygrad/__init__.py, src/mygrad/tensor_base.py, src/mygrad/tensor_manip/array_shape/funcs.py, src/mygrad/tensor_manip/array_shape/ops.py, tests/custom_strategies/__init__.py, tests/custom_strategies/test_strategies.py, tests/tensor_ops/test_reshape.py
- normalize reshape interface to match numpy exactly 
- make shape settable
- improve reshape testing
=> Reshape improvements

src/mygrad/nnet/initializers/__init__.py, src/mygrad/nnet/initializers/he_normal.py, tests/nnet/initializers/test_he_normal.py
Bad branching so you can ignore the changes to test_glorot_normal :/ those are in a different pr and I'll make sure that merges first
=> Add he_normal activation

docs/source/changes.rst, docs/source/generated/mygrad.nnet.initializers.glorot_normal.rst, docs/source/generated/mygrad.nnet.initializers.glorot_uniform.rst, docs/source/generated/mygrad.nnet.initializers.he_normal.rst, docs/source/generated/mygrad.nnet.initializers.he_uniform.rst, docs/source/generated/mygrad.nnet.initializers.normal.rst, docs/source/generated/mygrad.nnet.initializers.uniform.rst, docs/source/generated/mygrad.nnet.losses.focal_loss.rst, docs/source/generated/mygrad.nnet.losses.negative_log_likelihood.rst, docs/source/generated/mygrad.nnet.losses.softmax_focal_loss.rst, docs/source/nnet.rst, src/mygrad/nnet/initializers/glorot_normal.py, src/mygrad/nnet/initializers/glorot_uniform.py, src/mygrad/nnet/initializers/he_normal.py, src/mygrad/nnet/initializers/he_uniform.py, src/mygrad/nnet/losses/focal_loss.py
- adds docs for new `nnet` features
- adjusts input arg names for `softmax_focal_loss` to be consistent with other losses
=> docs changes for release 1.7

src/mygrad/nnet/activations/glu.py, src/mygrad/nnet/initializers/glorot_normal.py, src/mygrad/nnet/initializers/glorot_uniform.py, src/mygrad/nnet/initializers/he_normal.py, src/mygrad/nnet/initializers/he_uniform.py, src/mygrad/nnet/losses/__init__.py, src/mygrad/nnet/losses/negative_log_likelihood.py, tests/nnet/losses/test_negative_log_likelihood.py, tests/wrappers/uber.py
- adds regression test to catch `constant=True` bug in nll loss
=> Fix constant=True for nll loss. Fix docstring sections

src/mygrad/__init__.py, src/mygrad/math/nondifferentiable.py, tests/math/unary/test_nondifferentiable.py
=> Add `mygrad.any` and `Tensor.any`

src/mygrad/tensor_core_ops/indexing.py
See https://github.com/numpy/numpy/issues/5922
Leads to a ~4x speedup in some initial cases:
=> use augmented add instead of add.at where possible in getitem

src/mygrad/tensor_base.py, tests/state_testing/test_state.py, tests/tensor_base/test_tensor.py
=> make Tensor.constant settable

src/mygrad/tensor_base.py, tests/tensor_base/test_tensor.py, tests/tensor_ops/test_getitem.py, tests/tensor_ops/test_iter.py
=> permit indexing into 0d arrays

setup.cfg, src/mygrad/__init__.py, src/mygrad/numpy_compat/__init__.py, src/mygrad/numpy_compat/array_creation.py, tests/custom_strategies/__init__.py, tests/custom_strategies/test_strategies.py, tests/numpy_compat/test_array_creation.py
The first of many convenience functions for interchanging between arrays and tensors
Also adds `tensors` hypothesis strategy
=> Add asarray

src/mygrad/tensor_base.py, tests/tensor_base/test_augmented_updates.py
I was trying to parameterize this and invoke e.g. `getattr(x, "__imul__")`, but this seemed to not work for some reason.. also it was so gross to read/write
=> add tests for augmented updates

tests/tensor_base/test_chainrule.py, tests/tensor_base/test_graph_tracking.py
@petarmhg if you have some time, it would be great if you could double check my math on the gradients (just in case, somehow, I have made a mistake in my math that mirrors a mistake in the central backprop mechanism)
=> Improve simple graph checks

src/mygrad/__init__.py, src/mygrad/tensor_base.py, tests/custom_strategies/__init__.py, tests/tensor_base/test_tensor.py, tests/test_tensor_creation.py
=> Add astensor

src/mygrad/_utils/duplicating_graph.py, src/mygrad/_utils/lock_management.py, src/mygrad/linalg/ops.py, src/mygrad/operation_base.py, src/mygrad/tensor_base.py, src/mygrad/tensor_core_ops/indexing.py, src/mygrad/tensor_manip/transpose_like/ops.py, tests/linalg/test_einsum.py, tests/tensor_base/test_no_null_grad_semantics.py, tests/test_in_place_semantics.py, tests/test_tensor_manip.py, tests/test_utils.py
Also;
- fixes `Tensor.T` not returning views
- replaces some `shares_memory` checks with faster view checks
=> Add support for inplace updates on views of tensors

docs/source/autodiff_utils.rst, docs/source/conf.py, docs/source/generated/mygrad.mem_guard_off.rst, docs/source/generated/mygrad.mem_guard_on.rst, docs/source/generated/mygrad.no_autodiff.rst, docs/source/generated/mygrad.turn_memory_guarding_off.rst, docs/source/generated/mygrad.turn_memory_guarding_on.rst, docs/source/index.rst, src/mygrad/_utils/graph_tracking.py
Adds  docs for mem-guard utils and no-autodiff modes
=> Update docs for 2.0 features

docs/source/changes.rst, docs/source/generated/mygrad.Tensor.grad.rst, docs/source/generated/mygrad.Tensor.null_grad.rst, docs/source/index.rst, docs/source/intro.rst, docs/source/performance_tips.rst, docs/source/tensor.rst, docs/source/views.rst, src/mygrad/_tensor_core_ops/indexing.py, src/mygrad/_utils/__init__.py, src/mygrad/computational_graph.py, src/mygrad/nnet/initializers/glorot_normal.py, src/mygrad/nnet/initializers/normal.py, src/mygrad/nnet/initializers/uniform.py, src/mygrad/operation_base.py, src/mygrad/random/funcs.py, src/mygrad/tensor_base.py, src/mygrad/tensor_creation/funcs.py, tests/conftest.py, tests/custom_strategies/__init__.py, tests/state_testing/test_view_semantics.py, tests/tensor_base/test_op_wrapper.py, tests/tensor_base/test_scalar_only.py, tests/tensor_base/test_tensor.py, tests/wrappers/test_uber.py
Closes #317 
Adds docs and a changelog for v 2.0! 
Also makes `Operation` and `BroadcastableOp` abstract base classes
Also adds some tests for no auto-diff mode
=> More docs and minor tweaks for 2.0

src/mygrad/_utils/duplicating_graph.py, src/mygrad/math/arithmetic/ops.py, src/mygrad/operation_base.py, src/mygrad/tensor_base.py, src/mygrad/typing/_array_like.py, src/mygrad/typing/_dtype_like.py, tests/tensor_base/test_dtype_init.py, tests/tensor_base/test_tensor.py, tests/test_constant_inference.py, tests/test_ufuncs.py, tests/test_where_mask.py
Also permits boolean dtypes (treated like ints)
=> Support backprop through where mask

src/mygrad/__init__.py, src/mygrad/_dtype_mirrors.py, tests/test_dtype_mirrors.py
```python
>>> import mygrad as mg
>>> mg.float32
numpy.float32
```
=> mirror numpy dtypes that are valid for tensors

docs/source/changes.rst, docs/source/generated/mygrad.stack.rst, docs/source/tensor_manipulation.rst, src/mygrad/tensor_manip/tensor_joining/funcs.py, src/mygrad/tensor_manip/tensor_joining/ops.py, tests/test_tensor_joining.py
Co-authored-by: Petar Griggs <petargriggs@gmail.com>
=> add mygrad.stack

.github/workflows/tox_run.yml, README.md, setup.cfg, setup.py, tests/nnet/layers/test_batchnorm.py
Also add tests for Python 3.10
=> NEP 29: min numpy is now 1.19 

src/mygrad/tensor_base.py, tests/tensor_base/test_tensor.py
=> add Tensor.__index__ method

docs/source/changes.rst, docs/source/generated/mygrad.load.rst, docs/source/generated/mygrad.save.rst, docs/source/index.rst, docs/source/install.rst, docs/source/io.rst, src/mygrad/tensor_base.py, src/mygrad/tensor_manip/array_shape/funcs.py
Also improves some type annotations and docstrings.
=> Docs for 2.1.0
